### ISSUE TITLE
what do I have to commit?

### ISSUE THREAD

**Issue by hutomosaktikartiko** [anirudh-jwala/hacktoberfest-flutter#11]

**Comment by anirudh-jwala** [comment]
Use the repository to showcase your skills in Flutter by adding some worth sharing with world and your potential employer, fork-add project-add screenshots-send pull request

**Comment by hutomosaktikartiko** [comment]
> Use the repository to showcase your skills in Flutter by adding some worth sharing with world and your potential employer, fork-add project-add screenshots-send pull request

please check my PR
